mobile_base_controller:
  type: "diff_drive_controller/DiffDriveController"
  left_wheel: 'wheel_left_joint'
  right_wheel: 'wheel_right_joint'
  publish_rate: 51.0 # defaults to 50
  pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]
  twist_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 1000.0]

  # Wheel separation and radius multipliers for REEMH3-2
  wheel_separation_multiplier: 1.03 
  wheel_radius_multiplier: 1.0

  # Threshold to consider cmd_vel commands old [s] 
  cmd_vel_old_threshold: 1.0
