head_traj_controller:
  type: "robot_mechanism_controllers/JointTrajectoryActionController"
  joints:
    - head_1_joint
    - head_2_joint
  joint_trajectory_action_node:
    joints:
      - head_1_joint
      - head_2_joint
    constraints:
      goal_time: 0.6
      head_1_joint:
        goal: 0.02
      head_2_joint:
        goal: 0.02
